# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=20)),
                ('local', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('redesocial', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyinn', models.IntegerField()),
                ('qtd_rebuy', models.IntegerField()),
                ('pontuacao', models.IntegerField()),
                ('posicao', models.IntegerField()),
                ('premio', models.FloatField()),
                ('id_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneio.Etapa')),
                ('id_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneio.Players')),
            ],
        ),
        migrations.CreateModel(
            name='Torneios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torneio', models.CharField(max_length=20)),
                ('qtd_etapas', models.IntegerField()),
                ('qtd_players', models.IntegerField()),
                ('qtd_rebuy', models.IntegerField()),
                ('vlr_buyinn', models.FloatField()),
                ('vlr_rebuy', models.FloatField()),
                ('vlr_jackpot', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='ranking',
            name='id_torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneio.Torneios'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='id_torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneio.Torneios'),
        ),
    ]
