# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ('data',)},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ('player',)},
        ),
        migrations.AlterModelOptions(
            name='torneios',
            options={'ordering': ('torneio',)},
        ),
        migrations.AddField(
            model_name='players',
            name='nick',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
